[las]
#the standard deviation of the Gaussian input noise that is added during training
std_input_noise = 0.6
#number of pyramidal layers in the listener a non-pyramidal layer is added
#at the end
listener_numlayers = 3
#number of units in the listener
listener_numunits = 256
#listener dropout rate
listener_dropout = 0.5
listener_cell = gru
listener_activation = relu
#number of layers in the speller
speller_numlayers = 3
#number of units in the speller
speller_numunits = 256
#speller dropout rate
speller_dropout = 0.5
#the probability that the network will sample from the output during training
speller_sample_prob = 0.1
speller_cell = gru
speller_activation = relu
#the amount of labels that should be added at the output (e.g. blank, <eos>, ..)
add_labels = 1
max_input_length = 1000
max_target_length = 200

